language: go

branches:
  only:
    - dev-add-travis

go:
  - "1.11.x"
  - master

dist: trusty
sudo: false

# Dependencies handled, bypass Travis go get call.
install: true

# Build and run all tests (including subfolders.)
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -v ./...
